namespace PIBLib
{
    public enum EmitterFlag2v43 : int
    {
        eFLG_FLOW = 1 << 0x0,
        eFLG_DRAW_SHADOW = 1 << 0x1,
        eFLG_METABALL_HIGH_LIGHT = 1 << 0x2,
        eFLG_FIX_AXIS = 1 << 0x3,
        eFLG_ALPHA_THRESHOLD = 1 << 0x4,
        eFLG_SHADOW = 1 << 0x5,
        eFLG_NEAR_FADE = 1 << 0x6,
        eFLG_VTX_QUAD = 1 << 0x7,
        eFLG_COLOR_BLEND_MULTIPLE = 1 << 0x8,
        eFLG_SORT = 1 << 0x9,
        Flag11 = 1 << 10,
        eFLG_BLUR = 1 << 11,
        eFLG_ATTENUATION_SPEED = 1 << 12,
        eFLG_ATTENUATION_SPEED_MINUS = 1 << 13,
        eFLG_COLLISION = 1 << 14,
        eFLG_SCALE_ANIM_MULTIPLE = 1 << 15,
        eFLG_CHECK_DRAW_MASK = 1 << 16,
        eFLG_BLUR_MULTI = 1 << 17,
        eFLG_UNKV29_1 = 1 << 18,
        eFLG_UNKV43_2 = 1 << 19,
        eFLG_UNKV43_3 = 1 << 20,
        eFLG_VECTOR_FIELD = 1 << 21,
        eFLG_VECTOR_FIELD_ANIM = 1 << 22,
        eFLG_VECTOR_FIELD_LIFE = 1 << 23,
        eFLG_UNKV43_4 = 1 << 24,
        eFLG_TRACK = 1 << 25,
        eFLG_TRACK_CROSS = 1 << 26,
        eFLG_TRACK_OVERWRITE = 1 << 27,
        eFLG_TRACK_NOISE = 1 << 28,
        eFLG_CURL_NOISE = 1 << 29,
        eFLG_TIME_FADE = 1 << 30,
        eFLG_GATHER = 1 << 31,
    }
}
